program iDeasMain;

uses
  Forms,
  U_Main in 'U_Main.pas' {MainFrm},
  U_ChangePassword in 'U_ChangePassword.pas' {ChangePasswordFrm},
  U_Login_User in 'U_Login_User.pas' {Login_UserFrm},
  U_Splash in 'U_Splash.pas' {SplashFrm},
  U_LoginDB in 'U_LoginDB.pas' {LoginDBfrm},
  U_Supplier in 'U_Supplier.pas' {SupplierFrm},
  U_DM in 'U_DM.pas' {DM: TDataModule},
  U_Customer in 'U_Customer.pas' {CustomerFrm},
  U_Item in 'U_Item.pas' {ItemFrm},
  U_Salesman in 'U_Salesman.pas' {SalesmanFrm},
  UserMenu in 'UserMenu.pas' {UserMenuFrm},
  U_RekeningGL in 'U_RekeningGL.pas' {RekeningGLFrm},
  U_Transaction in 'U_Transaction.pas' {TransactionFrm},
  U_Currency in 'U_Currency.pas' {CurrencyFrm},
  U_KasKeluar in 'U_KasKeluar.pas' {KasKeluarFrm},
  U_KasMasuk in 'U_KasMasuk.pas' {KasMasukFrm},
  U_NotaHutang in 'U_NotaHutang.pas' {NotaHutangFrm},
  U_BankKeluar in 'U_BankKeluar.pas' {BankKeluarFrm},
  U_BankMasuk in 'U_BankMasuk.pas' {BankMasukFrm},
  U_BankRekonsiliasi in 'U_BankRekonsiliasi.pas' {BankRekonsiliasiFrm},
  U_NotaDebet in 'U_NotaDebet.pas' {NotaDebetFrm},
  U_InfoAPList in 'U_InfoAPList.pas' {InfoAPListFrm},
  U_NotaPiutang in 'U_NotaPiutang.pas' {NotaPiutangFrm},
  U_NotaKredit in 'U_NotaKredit.pas' {NotaKreditFrm},
  U_InfoARList in 'U_InfoARList.pas' {InfoARListFrm},
  U_Memorial in 'U_Memorial.pas' {MemorialFrm},
  U_JurnalPosting in 'U_JurnalPosting.pas' {JurnalPostingFrm},
  U_Status_Dialog in 'U_Status_Dialog.pas' {frmStatus_Dialog},
  U_TrialBalance in 'U_TrialBalance.pas' {TrialBalanceFrm},
  U_Unit in 'U_Unit.pas' {UnitFrm},
  U_Warehouse in 'U_Warehouse.pas' {WarehouseFrm},
  U_InfoNeraca in 'U_InfoNeraca.pas' {InfoNeracaFrm},
  U_InfoRL in 'U_InfoRL.pas' {InfoRLFrm},
  U_CashFlow in 'U_CashFlow.pas' {CashFlowFrm},
  U_RekKasBank in 'U_RekKasBank.pas' {RekKasBankFrm},
  U_InfoCashFlow in 'U_InfoCashFlow.pas' {InfoCashFlowFrm},
  U_InfoMatlStok in 'U_InfoMatlStok.pas' {InfoMatlStokFrm},
  U_BukuBank in 'U_BukuBank.pas' {BukuBankFrm},
  U_BukuKas in 'U_BukuKas.pas' {BukuKasFrm},
  U_AppLog in 'U_AppLog.pas' {AppLogFrm},
  U_ImportPiutang in 'U_ImportPiutang.pas' {ImportPiutangFrm},
  U_Parameter in 'U_Parameter.pas' {ParameterFrm},
  U_KasirTunai in 'U_KasirTunai.pas' {KasirTunaiFrm},
  U_PrintOption in 'U_PrintOption.pas' {PrintOptionFrm},
  U_InfoARSales in 'U_InfoARSales.pas' {InfoARSalesFrm},
  U_SaldoAwal in 'U_SaldoAwal.pas' {SaldoAwalFrm},
  U_KasirNonTunai in 'U_KasirNonTunai.pas' {KasirNonTunaiFrm},
  U_BukuKasir in 'U_BukuKasir.pas' {BukuKasirFrm},
  U_Kasbon in 'U_Kasbon.pas' {KasbonFrm},
  U_Karyawan in 'U_Karyawan.pas' {KaryawanFrm},
  U_Settlement in 'U_Settlement.pas' {SettlementFrm},
  U_SettingNeraca in 'U_SettingNeraca.pas' {SettingNeracaFrm},
  U_LookRekening in 'U_LookRekening.pas' {LookRekeningFrm},
  U_InfoNewNeraca in 'U_InfoNewNeraca.pas' {InfoNewNeracaFrm},
  U_LookRekeningRL in 'U_LookRekeningRL.pas' {LookRekeningRLFrm},
  U_SettingLari in 'U_SettingLari.pas' {SettingLariFrm},
  U_InfoNewRL in 'U_InfoNewRL.pas' {InfoNewRLFrm},
  U_StatusKasbon in 'U_StatusKasbon.pas' {StatusKasbonFrm},
  UDataObject in 'UDataObject.pas',
  U_NotaPromo in 'U_NotaPromo.pas' {NotaPromoFrm},
  U_LookPromo in 'U_LookPromo.pas' {LookPromoFrm},
  U_ImportHutang in 'U_ImportHutang.pas' {ImportHutangFrm},
  U_SetExcelString in 'U_SetExcelString.pas' {SetExcelStringFrm},
  U_SettingFaktur in 'U_SettingFaktur.pas' {SettingFakturFrm},
  U_InfoTPRList in 'U_InfoTPRList.pas' {InfoTPRListFrm},
  U_Talangan in 'U_Talangan.pas' {TalanganFrm},
  U_SettingBayar in 'U_SettingBayar.pas' {SettingBayarFrm},
  U_UpdateVoucher in 'U_UpdateVoucher.pas' {UpdateVoucherFrm},
  U_SetVoucher in 'U_SetVoucher.pas' {SetVoucherFrm},
  U_InfoItemBS in 'U_InfoItemBS.pas' {InfoItemBSFrm},
  U_CariRekanan in 'U_CariRekanan.pas' {CariRekananFrm},
  U_CariRekening in 'U_CariRekening.pas' {CariRekeningFrm},
  U_RepairItem in 'U_RepairItem.pas' {RepairItemFrm},
  U_JenisAset in 'U_JenisAset.pas' {JenisAsetFrm},
  U_AktivaTetap in 'U_AktivaTetap.pas' {AktivaTetapFrm},
  U_RepairCustomer in 'U_RepairCustomer.pas' {RepairCustomerFrm},
  U_RepairSales in 'U_RepairSales.pas' {RepairSalesFrm},
  U_DateTrans in 'U_DateTrans.pas' {DateTransFrm},
  U_DateCair in 'U_DateCair.pas' {DateCairFrm},
  U_MemorialUli in 'U_MemorialUli.pas' {MemorialUliFrm},
  U_LookPiutangUli in 'U_LookPiutangUli.pas' {LookPiutangUliFrm},
  U_Export in 'U_Export.pas' {ExportFrm},
  U_Import in 'U_Import.pas' {ImportFrm},
  U_ImportReturBeli in 'U_ImportReturBeli.pas' {ImportReturBeliFrm},
  U_ImportReturBungah in 'U_ImportReturBungah.pas' {ImportReturBungahFrm},
  U_ImportHutang2 in 'U_ImportHutang2.pas' {ImportHutang2Frm},
  U_IkhtisarPenjualan in 'U_IkhtisarPenjualan.pas' {IkhtisarPenjualanFrm},
  U_InfoVoucherList in 'U_InfoVoucherList.pas' {InfoVoucherListFrm},
  U_ImportVoucher2 in 'U_ImportVoucher2.pas' {ImportVoucher2Frm},
  U_LookHutangUli in 'U_LookHutangUli.pas' {LookHutangUliFrm},
  U_ImportPiutangMayora in 'U_ImportPiutangMayora.pas' {ImportPiutangMayoraFrm},
  U_InfoAgeAR in 'U_InfoAgeAR.pas' {InfoAgeARFrm},
  U_InfoMatlStok2 in 'U_InfoMatlStok2.pas' {InfoMatlStok2Frm},
  U_ItemReceive in 'U_ItemReceive.pas' {ItemReceiveFrm},
  U_PengeluaranBarang in 'U_PengeluaranBarang.pas' {PengeluaranBarangFrm},
  U_LapNilaiSediaan in 'U_LapNilaiSediaan.pas' {LapNilaiSediaanFrm},
  U_StokAwal in 'U_StokAwal.pas' {StokAwalFrm},
  U_Verifikasi in 'U_Verifikasi.pas' {VerifikasiFrm},
  U_Pencarian in 'U_Pencarian.pas' {PencarianFrm},
  U_InventoryAdjusment in 'U_InventoryAdjusment.pas' {InventoryAdjusmentFrm},
  U_Ref_NoFaktur in 'U_Ref_NoFaktur.pas' {RefNoFakturFrm},
  U_List_FakturPenjualan in 'U_List_FakturPenjualan.pas' {ListFakturPenjualanFrm},
  U_ImportPembelianMayora in 'U_ImportPembelianMayora.pas' {TfrmImportFakturPembelianMayora},
  U_RepairData in 'U_RepairData.pas' {frmRepairData},
  U_NotaRetail in 'U_NotaRetail.pas' {NotaRetailFrm},
  U_MGudang in 'U_MGudang.pas' {MGudangFrm},
  U_LapPembelian in 'U_LapPembelian.pas' {LapPembelianFrm},
  U_LapUmurHutang in 'U_LapUmurHutang.pas' {LapUmurHutangFrm},
  U_MutasiStok in 'U_MutasiStok.pas' {MutasiStokFrm},
  U_LapPenjualan in 'U_LapPenjualan.pas' {LapPenjualanFrm},
  U_LapKasirPerShift in 'U_LapKasirPerShift.pas' {LapKasirPerShiftFrm},
  U_KertasKerja in 'U_KertasKerja.pas' {KertasKerjaFrm},
  U_BayarNotaPenjualan in 'U_BayarNotaPenjualan.pas' {BayarNotaPenjualanFrm},
  U_ItemCheck in 'U_ItemCheck.pas' {ItemCheckFrm},
  U_LapSetoran in 'U_LapSetoran.pas' {LapSetoranFrm},
  U_NotaOnline in 'U_NotaOnline.pas' {NotaOnlineFrm};

{$R *.res}

begin
  Application.Initialize;
  with TSplashFrm.Create(Application) do
    try
      ShowModal;
    finally
      Free;
    end;
  Application.Title := 'iDeasPOS';
  Application.CreateForm(TDM, DM);
  if DM.conn.Connected  then begin
     Application.CreateForm(TMainFrm, MainFrm);
     Application.CreateForm(TDateTransFrm, DateTransFrm);
  end;
  Application.Run;
end.
